name: update data

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup dependencies
        run: |
          npm ci
          npm run build
          cd lambda
          npm ci

    
      - name: Get json file
        run: |
            npm run update:data

      - name: commit and push
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: update data
          commit_user_name: update data bot
          commit_user_email: sassy.watanabe@gmail.com>
          commit_author: update data bot <sassy.watanabe@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@master
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'ClovaExtensionTokyoCovid19PositiveCountStack'
          cdk_version: '1.144.0'
          actions_comment: false
          args: '--require-approval never'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@master
        with:
          cdk_subcommand: 'synth'
          cdk_version: '1.144.0'
          cdk_stack: 'ClovaExtensionTokyoCovid19PositiveCountStack'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-northeast-1'




